CREATE DATABASE ExploreSpace;

USE ExploreSpace;

CREATE TABLE Users(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE Trips(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nameTrip VARCHAR(50) NOT NULL,
    duration INT NOT NULL,
    date VARCHAR(50) NOT NULL ,
    planet VARCHAR(50) NOT NULL,
    passangers INT NOT NULL,
    conductor VARCHAR(50) NOT NULL  
);

CREATE TABLE Tripstaken(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userID INT NOT NULL,
    tripID INT NOT NULL
);

ALTER TABLE Users ADD rol VARCHAR(10) NOT NULL DEFAULT 'user';

DESCRIBE Users;

DESCRIBE Trips;