"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.api_key = exports.expires_in = exports.secret_token = exports.db_name = exports.db_host = exports.db_password = exports.db_user = exports.port = void 0;
const dotenv_1 = require("dotenv");
dotenv_1.config();
exports.port = process.env.PORT;
exports.db_user = process.env.DB_USER;
exports.db_password = process.env.DB_PASSWORD;
exports.db_host = process.env.DB_HOST;
exports.db_name = process.env.DB_NAME;
exports.secret_token = process.env.SECRET_TOKEN;
exports.expires_in = process.env.EXPIRES_IN;
exports.api_key = process.env.API_KEY;
